# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_node <- function() {
    .Call('_relater_test_node', PACKAGE = 'relater')
}

#' Multiply a number by two
#'
#' @param x A single integer.
#' @examples
#' timesTwo(2)
#' @export
timesTwo <- function(x) {
    .Call('_relater_timesTwo', PACKAGE = 'relater', x)
}

